### ISSUE TITLE
MacOS Visualization Tab > View results in java.lang.NoClassDefFoundError: javax/media/opengl/GLException

### ISSUE THREAD

**Issue by JustasB** [NeuralEnsemble/neuroConstruct#53]
On MacOS 10.10.3, with Java 1.8.0.66 installed, clicking "View" in the "Visualization" tab displays nothing, and the console shows the following error:

```
15:10:06.141> UncaughtExceptionInfo  : *** ERROR*** : java.lang.NoClassDefFoundError: javax/media/opengl/GLException
15:10:06.141> UncaughtExceptionInfo  : *** ERROR*** : 	at java.lang.Class.forName0(Native Method)
15:10:06.141> UncaughtExceptionInfo  : *** ERROR*** : 	at java.lang.Class.forName(Class.java:264)
15:10:06.141> UncaughtExceptionInfo  : *** ERROR*** : 	at javax.media.j3d.Pipeline$1.run(Pipeline.java:143)
15:10:06.142> UncaughtExceptionInfo  : *** ERROR*** : 	at java.security.AccessController.doPrivileged(Native Method)
15:10:06.142> UncaughtExceptionInfo  : *** ERROR*** : 	at javax.media.j3d.Pipeline.createPipeline(Pipeline.java:138)
15:10:06.142> UncaughtExceptionInfo  : *** ERROR*** : 	at javax.media.j3d.MasterControl.loadLibraries(MasterControl.java:926)
15:10:06.142> UncaughtExceptionInfo  : *** ERROR*** : 	at javax.media.j3d.VirtualUniverse.<clinit>(VirtualUniverse.java:280)
15:10:06.143> UncaughtExceptionInfo  : *** ERROR*** : 	at javax.media.j3d.GraphicsConfigTemplate3D.getBestConfiguration(GraphicsConfigTemplate3D.java:302)
15:10:06.143> UncaughtExceptionInfo  : *** ERROR*** : 	at java.awt.GraphicsDevice.getBestConfiguration(GraphicsDevice.java:207)
15:10:06.143> UncaughtExceptionInfo  : *** ERROR*** : 	at ucl.physiol.neuroconstruct.j3D.OneCell3DPanel.repaint3DScene(OneCell3DPanel.java:590)
```

Searching SO and elsewhere, and then following the steps below to install Java3D, results in the error below

Steps: https://gouessej.wordpress.com/2012/08/01/java-3d-est-de-retour-java-3d-is-back/

```
java.lang.NoClassDefFoundError: javax/media/opengl/GLCapabilitiesChooser
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at javax.media.j3d.Pipeline$1.run(Pipeline.java:143)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.media.j3d.Pipeline.createPipeline(Pipeline.java:138)
	at javax.media.j3d.MasterControl.loadLibraries(MasterControl.java:926)
	at javax.media.j3d.VirtualUniverse.<clinit>(VirtualUniverse.java:280)
	at javax.media.j3d.GraphicsConfigTemplate3D.getBestConfiguration(GraphicsConfigTemplate3D.java:302)
	at java.awt.GraphicsDevice.getBestConfiguration(GraphicsDevice.java:207)
	at ucl.physiol.neuroconstruct.j3D.OneCell3DPanel.repaint3DScene(OneCell3DPanel.java:590)

```

**Comment by borismarin** [comment]
@JustasB could you have a look at https://github.com/openworm/OpenWorm/issues/93 ?
